### PR TITLE
Add Sepia, blur, and reflect functions to filters

### PR DESCRIPTION
**Pull request by travissouthard**
## Overview

These changes wrap up week 4 with the remaining filter functions that all appear to be working well at a basic level.

## Testing:

- Pull down this branch
- In the `week-4` folder run:
  -  `./run-filter.sh -b images/stadium.bmp blur.bmp
`
    - Check the new `blur.bmp` image and make sure it is successfully blurred without distorting colors
  -  `./run-filter.sh -r images/courtyard.bmp reflect.bmp
`
    - Check the new `reflect.bmp` image and make sure it is successfully reflected without distorting colors
  -  `./run-filter.sh -s images/tower.bmp sepia.bmp
`
    - Check the new `sepia.bmp` image and make sure it is successfully changes color to a monochrome warm yellow

### CODE REVIEW

**Comment by travissouthard** [comment]
Also huge thanks to Adeel for the hint on finishing the blur function!

**Review by ktohalloran — APPROVED** [review]
Looks great! I'm sorry I missed implementing the blur function but it's neat to see what y'all came up with--I was especially curious about how you account for the edges of the picture.

**Comment by travissouthard** [comment]
> I was especially curious about how you account for the edges of the picture.

https://github.com/azavea/cs-fundamentals-group/blob/4f3594d61b194daec58f8fd435d454b29270ad45/cs-50/week-4/helpers.c#L85-L86

Yeah this is a clunky line and I want to rewrite it as a variable called `pixel exists` but there's no `boolean` type in c without a library and the one I tried misbehaved. It essentially checks if the `i` or `j` is less than 0 or greater than the array length. In JS or python, I would set that as its own variable for readability.

**Review by rachelekm — APPROVED** [review]
Sweet! Great fix to the issue we were bumping into 👍 
I also added a quick commit to modify our CI so that our build could pass (I guess we needed to link the math library to the compiler used by GA now that we include it)

**Comment by travissouthard** [comment]
> Sweet! Great fix to the issue we were bumping into 👍 I also added a quick commit to modify our CI so that our build could pass (I guess we needed to link the math library to the compiler used by GA now that we include it)

Ah! Good find! I was wondering why it ran into an issue, despite working locally.

**Pull request merged**
