### PR TITLE
WIP for W4PS1

### PR DESCRIPTION
**Pull request by rachelekm**
WIP Solution for [Week 4 Problem Set 1](https://cs50.harvard.edu/x/2022/psets/4/filter/less/) from 6-10-22

To implement the program, run with filter flag arguments and name of the image file followed by name of output file, like below:
```
$ ./run-filter.sh -g images/yard.bmp out.bmp
```

## Notes
- We had to update our `run-filter` script to account for multiple files to be compiled as well delete the previously compiled output before re-compiling in order for it to function.

### CODE REVIEW

**Comment by travissouthard** [comment]
The images didn't make it in the changes or I missed a step that I'm not seeing.

**Comment by rachelekm** [comment]
Whoops, thanks for catching that! I removed images from the `.gitignore` but forgot to refresh the cache—they should be up now.

**Review by travissouthard — APPROVED** [review]
This is working well and reads correctly to me.
The grayscale is a simple algorithm but I want to make sure we are cognizant of keeping the others as neatly written. Looking ahead, the next few helpers might blow up in messiness.

**Review by ktohalloran — APPROVED** [review]
👍

**Pull request merged**
