### PR TITLE
Add nand2tetris project files & Not, And, Or chip solutions

### PR DESCRIPTION
**Pull request by ktohalloran**
I won't be able to come to the next meeting so wanted to push up the code for the Not, And, and Or chips that we wrote last time we met. This also adds all the new stuff for the `nand2tetris` course, except for the `tools` folder, which I added to the `.gitignore`. Also, here's the link to the [Jamboard](https://jamboard.google.com/d/16Huif72BOp3aipfzo7knEq_FTA386sHUrMk15K2U9fY/viewer?f=0) that we were drawing on for visual references to go along with our code. We left off having drawn a picture of the long method for creating a Xor chip in the Jamboard but hadn't turned it into hdl.

### CODE REVIEW

**Review by rachelekm — APPROVED** [review]
Thanks for putting this together!

**Comment by ktohalloran** [comment]
Just pushed up all of the solutions except for the last chip, the DMux8Way which I'll try to add sometime next week. I've also added the consolidated truth tables file for the Nand, And, Or, Xor, Mux, and DMux chips. For Mux and DMux, I tried to make the tables a little easier to read by bolding the input that the selector is pointing to. Hopefully that helps!

**Comment by ktohalloran** [comment]
Ok, just pushed up the last solution for the DMux8Way gate 🎉 all solutions should have corresponding drawings in the [Jamboard](https://jamboard.google.com/d/16Huif72BOp3aipfzo7knEq_FTA386sHUrMk15K2U9fY/edit?usp=sharing). As a note, one thing that caught me up while working on this was that the bus pin indexes run the opposite direction of array indexes, so say we have `sample_val = 001`, normal indexing says `sample_val[0] = 0`, `sample_val[2] = 1`, but if it were a bus pin that we were trying to sub-bus, `sample_val[0] = 1` and `sample_val[2] = 0` (I've attached the picture I've been using to remember this in case that's helpful). Similarly, writing sub-busses with multiple pins uses syntax like `[0..1]` to isolate the pins at indexes 0 and 1, where the ending index is inclusive, rather than the `[0:2]` that we're used to seeing.

Screen Shot 2022-11-03 at 8 32 05 AM

**Review by travissouthard — APPROVED** [review]
Thanks for pushing these up!
Was very helpful in having these to reference while Rachele and I got caught up!

**Pull request merged**
