### PR TITLE
Complete the Caesar problem from problemset 1

### PR DESCRIPTION
**Pull request by travissouthard**
# Overview

This should be the complete solution to the Caesar problem in the [problemset 2 of the CS-50 course](https://cs50.harvard.edu/x/2022/psets/2/caesar/), made while pairing with @pomadchin & @rachelekm.

# Demo

image

### CODE REVIEW

**Review by pomadchin — COMMENTED** [review]
I'd prefer to inline rotations, but LGTM; 
how about restructuring repo a bit? 

i.e. 

* `./cs-50/libcs50-10.1.1`
* `./cs-50/week-n`

and symlink if sources are needed into the `week-n` via `ln -s libcs50-10.1.1 ./week-n/libcs50-10.1.1`?

**Comment by travissouthard** [comment]
> I'd prefer to inline rotations, but LGTM; how about restructuring repo a bit?
> 
> i.e.
> 
> * `./cs-50/libcs50-10.1.1`
> * `./cs-50/week-n`
> 
> and symlink if sources are needed into the `week-n` via `ln -s libcs50-10.1.1 ./week-n/libcs50-10.1.1`?

Would you be able to comment in the files changed to indicate how you'd like the inline rotations to work?

Also I love the idea of restructuring the repo, especially to reduce how many times libraries need to be copied. I've never used `ln` before but I think that sounds like a good solution.

**Comment by pomadchin** [comment]
Check out the commit [19cf43a](https://github.com/azavea/cs-fundamentals-group/pull/5/commits/19cf43a371019ca1adc7b3516f9b09c014eeafc9)

**Review by rachelekm — APPROVED** [review]
Looks great! @pomadchin thanks for the tests and repo restructure 👍

**Pull request merged**
